/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "MessageHandler.h"
#include "string.h"
/* Header for class EnclaveBridge */

#ifndef _Included_EnclaveBridge
#define _Included_EnclaveBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnclaveBridge
 * Method:    createMessageHandlerOBJ
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_EnclaveBridge_createMessageHandlerOBJ
  (JNIEnv *, jobject);

/*
 * Class:     EnclaveBridge
 * Method:    handleVerification
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleVerification
  (JNIEnv *, jobject, jlong);

/*
 * Class:     EnclaveBridge
 * Method:    handleMSG0
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleMSG0
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     EnclaveBridge
 * Method:    handleMSG2
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleMSG2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     EnclaveBridge
 * Method:    handleAttestationResult
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleAttestationResult
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
