/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "MessageHandler.h"
/* Header for class EnclaveBridge */

#ifndef _Included_EnclaveBridge
#define _Included_EnclaveBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnclaveBridge
 * Method:    createMessageHandlerOBJ
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_EnclaveBridge_createMessageHandlerOBJ
  (JNIEnv *, jobject);

/*
 * Class:     EnclaveBridge
 * Method:    handleMessages
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_EnclaveBridge_handleMessages
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
