/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sgxtrial_yyy_EnclaveBridge */

#ifndef _Included_com_sgxtrial_yyy_EnclaveBridge
#define _Included_com_sgxtrial_yyy_EnclaveBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sgxtrial_yyy_EnclaveBridge
 * Method:    createMessageHandlerOBJ
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sgxtrial_yyy_EnclaveBridge_createMessageHandlerOBJ
  (JNIEnv *, jobject);

/*
 * Class:     com_sgxtrial_yyy_EnclaveBridge
 * Method:    handleMessages
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sgxtrial_yyy_EnclaveBridge_handleMessages
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
