/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sgxtrial_yyy_Bridge */

#ifndef _Included_com_sgxtrial_yyy_Bridge
#define _Included_com_sgxtrial_yyy_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sgxtrial_yyy_Bridge
 * Method:    sgxCreateEnclave
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_sgxtrial_yyy_Bridge_sgxCreateEnclave
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_sgxtrial_yyy_Bridge
 * Method:    doAttestation
 * Signature: (Ljava/lang/String;Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_com_sgxtrial_yyy_Bridge_doAttestation
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
