/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnclaveBridge */

#ifndef _Included_EnclaveBridge
#define _Included_EnclaveBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnclaveBridge
 * Method:    handleVerification
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleVerification
  (JNIEnv *, jobject);

/*
 * Class:     EnclaveBridge
 * Method:    handleMSG0
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleMSG0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     EnclaveBridge
 * Method:    handleMSG2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleMSG2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     EnclaveBridge
 * Method:    handleAttestationResult
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EnclaveBridge_handleAttestationResult
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
